config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  as :user do
    get 'my_account/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'my_account/' => 'registrations#update', :as => 'update_user_registration'
    get 'my_account' => 'registrations#show', :as => 'user_registration'
    end
  get '/myarticles' => 'users#article'
  
  resources :groups, only: [:index, :show] do
    get '/myarticles' => 'users#article'
    resources :categories, except: [:index] do
      collection do
          get 'search'
          get 'autocomplete'
    	 end
      resources :articles do
        collection do
          get 'search'
          get :deleted
    	  end
    	  member do
          get :toggle_status
          put :follow
          put :unfollow
        end
    	  resources :versions, only: [:destroy] do
           member do
            get :diff, to: 'versions#diff'
            patch :rollback, to: 'versions#rollback'
          end
        end
      end
    end
  end
  
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  mount ActionCable.server => '/cable'
  root to: "groups#index"
end

app/models/article.rb
class Article < ApplicationRecord
  acts_as_paranoid
  is_impressionable :counter_cache => true, :column_name => :impressions_count
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :name, use: :slugged
  acts_as_taggable 
  acts_as_votable
  belongs_to :category
  belongs_to :user
  has_many :comments
  has_many :article_uploads, dependent: :destroy
  accepts_nested_attributes_for :article_uploads,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['attachment'].blank?}
  has_paper_trail class_name:'Version'
  
  validates_presence_of :name, :description, :body
  searchkick word: [:name, :description, :body, :category_id]
  after_commit :reindex
  
  def search_data
    {
      name: name,
      description: description,
      body: body,
      category_id: category_id
    }
  end
  def category_name
    category.try(:slug)
  end
  
  scope :latest, -> { order("Id DESC") }
  
  def user_name
    user ? user.name : ''
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_group
  before_action :set_category
  before_action :set_paper_trail_whodunnit
  before_action :set_article, only: [:show, :edit, :update, :destroy, :follow, :unfollow, :toggle_status]
  before_action :set_topic, only: [:search]
  before_action :authenticate_user!
  impressionist actions: [:show], unique: [:session_hash]
  access user: {except: [:new, :edit, :destroy, :deleted]}, editor: :all, admin: :all
  
  def search
    if params[:search]
      @articles = Article.page.where('name ILIKE ?', "%" + params[:search] + "%" ).where(category_id: @category.id).per(5).latest
    end 
  end
  
  def index
    @categories = Category.all
    
    case
      when params[:category]
        @articles = Article.where(category_id: params[:category]).page(params[:page]).per(10).latest
      when params[:tag]
        @articles = Article.page.tagged_with(params[:tag]).per(5).latest
      else
        @articles = Article.all
    end
  end
  
  def show
    @article = Article.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
    impressionist(@article, "message...")
    @versions =@article.versions.order('created_at DESC')
  end
  
  def new
    @article = Article.new
  end
  
  def create
     @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to group_category_article_path(@group, @category, @article), notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit
    @versions =@article.versions.order('created_at DESC')
  end
  
  def update
    @following = @article.votes_for.up.by_type(User).voters
    respond_to do |format|
      if @article.update(article_params)
        @following.each do |f|
          notifier = Slack::Notifier.new f.slack_url
          @user = User.find(@article.versions.last.whodunnit)
          @message = "
          The article:  #{@article.name} was updated by: #{@user.name} click [here](http://localhost:3000#{group_category_article_path(@group, @category, @article)}) to view the article
          "
          a_ok_note = {
            fallback: "Everything looks peachy",
            text: Slack::Notifier::Util::LinkFormatter.format(@message),
            color: "#4e2a84",
            mrkdwn: true
          }
          notifier.ping text: "Hello #{f.first_name}", attachments: [a_ok_note]
        end
        format.html { redirect_to group_category_article_path(@group, @category, @article), notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to group_category_path(@group, @category), notice: 'Article was Removed.' }
    end
  end
  
  def deleted
    @articles = Version.where(event: 'destroy')
  end
  
  def follow 
    @article.upvote_by current_user
    redirect_to :back
  end  

  def unfollow
    @article.downvote_by current_user
    redirect_to :back
  end

  def toggle_status
    if @article.draft?
      @article.published!
    elsif @article.published?
      @article.draft!
    end
    redirect_to group_myarticles_url, notice: 'Article status has been updated.'
  end
  
  private
  
  def set_group
    @group = Group.friendly.find(params[:group_id])
  end
  
  def set_category
    @category = Category.friendly.find(params[:category_id])
  end
  
  def set_article
    @article= Article.friendly.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:name, 
                                    :description,
                                    :body,
                                    :link,
                                    :jira_ticket,
                                    :user_id,
                                    :category_id,
                                    :tag_list,
                                    :status,
                                    article_uploads_attributes: [:id, :attachment, :_destroy]
                                  )
  end
  
  def set_topic
    @topics= Topic.with_articles
  end
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
   def find_version_author_name(version)
    user = User.find_version_author(version) 
    user ? user.name : ''
  end
  
  def diff(content1, content2)
   changes = Diffy::Diff.new(content1, content2, 
                             include_plus_and_minus_in_html: true, 
                             include_diff_info: true)
   changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end

  def article_status_color article
    'color: red;' if article.draft?
  end
end

app/views/articles/_article_upload_fields.html.erb
<div class="form-group nested-fields">
  <label class="btn btn-primary">
    <%= fa_icon "upload"%> Upload Attachment <%= f.file_field :attachment, style: 'display:none;'%>
  </label>
  <label class="btn btn-danger">
  <%= link_to_remove_association 'Remove Image', f , class: 'remove'%>
  </label>
</div>

app/views/articles/_form.html.erb
<%= form_for([@group, category, article]) do |f| %>
  <% if article.errors.any? %>
    <% article.errors.full_messages.each do |error| %>
      <%= alert_generator error%>
    <%end%>
  <% end %>
  
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Title' %>
  </div>
  
  <div class="form-group">
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
  </div>
  
   <div class="form-group">
        <%= f.text_area :body, class: 'form-control', rows: 15, id:"article-body", placeholder: 'Content' %>
  </div>
      
  <div class="form-group">
    <%= f.text_field :tag_list, value: article.tag_list.to_s, class: 'form-control', placeholder: 'Tags (separated by commas)' %>
  </div>
  
  <div class="form-group">
    <%= f.collection_select(:category_id, @group.categories, :id, :name ,{include_blank: false}, {class: 'form-control '}) %>
  </div>
  
   <div class="form-group">
    <%= f.text_field :link, class: 'form-control', placeholder: 'Link' %>
  </div>
  
   <div class="form-group">
    <%= f.text_field :jira_ticket, class: 'form-control', placeholder: 'Ticket #' %>
  </div>
  
  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, "Draft"%>
    
    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, "Published"%>
  </div>
  
  <h2>Addtional Attachments:</h2>
  <div>
    <%= f.fields_for :article_uploads do |article_uploads_form|%>
      <%= render 'article_upload_fields', f: article_uploads_form %>
    <%end%>
  </div>
  
  <div>
    <%= link_to_add_association 'Add Attachment', f, :article_uploads, class: "btn btn-primary" %>
  </div>
      
  <%= f.hidden_field :user_id, value: current_user.id %>
  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/_searchbar.html.erb
<aside class="widget widget_search">
  <%= form_tag search_group_category_articles_path, method: :get, class: "navbar-form navbar-center", role: "search" do %>
      <p>
    <%=text_field_tag :search, params[:search], class: "form-control", id:'search_articles', autocomplte: :off, placeholder: "Hit enter to search..." %>
    <%= button_tag("Search", name: nil, class: "search-button") do%>
      <%= fa_icon "search"%>
    <%end%>
    </p>
 <%end%>   
</aside>

app/views/articles/_versions.html.erb
<h2>Previous Versions</h2>

<table class='table'>
  <thead>
    <tr>
      <th>Index</th>
      <th>Date</th>
      <th>Author</th>
      <th>Event</th>
      <th>Diff</th>
      <th>Rollback</th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.created_at %></td>
        <td><%= find_version_author_name(version) %></td>
        <td><%= version.event.humanize %></td>
        <td><%= link_to 'Diff',  diff_group_category_article_version_path(@group, @category, @article, version) %></td>
        <td><%= link_to 'Rollback', rollback_group_category_article_version_path(@group, @category, @article, version), method: 'PATCH' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/deleted.html.erb
<div class="uk-section">
  <div class="uk-container">
    
    <h1>List of deleted articles for <%= @category.name.capitalize!%></h1>
    <table class='table'>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Description</th>
          <th>Deleted by</th>
          <th>At</th>
          <th colspan="3">Bringback</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article_version| %>
          <%- article = article_version.reify %>
          <tr>
            <td><%= article.id %></td>
            <td><%= article.name %></td>
            <td><%= article.description %></td>
            <td><%= find_version_author_name(article_version) %></td>
            <td><%= article.created_at %></td>
            <td><%= link_to 'Bringback', bringback_version_path(article_version), method: 'PATCH' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to "Back", :back, class: "btn btn-primary" %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="uk-section">
  <div class="uk-container">
    <div class="col-sm-8 blog-main">
      <h1>Edit Article</h1>
      
      <%= render 'form', {category: @category, article: @article}  %>
      
      <%= link_to 'Show', group_category_article_path(@group, @category, @article), class: "btn btn-success" %> |
      <%= link_to 'Back', group_category_path(@group, @category), class: "btn btn-danger" %>
      
      <% if !@versions.empty?%>
        <%= render 'versions', {versions: @versions} %>
      <%end%>
      
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div class="row">
  <% @categories.each do |category|%>
    <div class="col-md-4">
      <div class="card category-box">
       
      </div>
    </div>
  <%end%>
</div>

<% @articles.each do |article|%>
  <h2><%= article.name %></h2>
  <h4><%= article.description %></h4>
  <p><%= markdown article.body %></p>
  Created by: <%= article.user.name %>
<%end%>
<br>
<%= paginate @articles %>

app/views/articles/new.html.erb
<div class="uk-section">
  <div class="uk-container">

    <div class="col-sm-8 blog-main">
      <h1>Create New Article</h1>
      <hr>
      
      <%= render 'form',  {category: @category, article: @article} %>
      
      <%= link_to "Back", :back, class: "btn btn-danger myspace" %>
    </div>
  </div>
</div>

app/views/articles/search.html.erb
<div class="uk-section section-sub-nav uk-padding-remove">
  <div class="uk-container">
    <h1>Articles</h1>
    
    <% @articles.each do |article|%>
      <h2><%= article.name %></h2>
      <h4><%= article.description %></h4>
      <p><%= markdown article.body %></p>
      Created by: <%= article.user.email %>
      <span class="badge btn-primary"><%= article.category.name%></span><
    <%end%>
    <%= paginate @articles %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="uk-section section-sub-nav uk-padding-remove">
  <div class="uk-container">
    <div uk-grid>
      <div class="uk-width-2-3@m">
        <ul class="uk-breadcrumb uk-visible@m">
          <li><%= link_to "Home", root_path %> </li>
          <li><%= link_to @category.name.capitalize, group_category_path(@group, @category)%></li>
          <li><span><%= link_to @article.name, group_category_article_path(@group, @category, @article)%></span></li>
        </ul>
      </div>
  </div>
   <div class="border-top"></div>
</div>

<div class="uk-section">
  <div class="uk-container">

    <h2 id="title"><%= @article.name %>
    <button class= "clipboard-btn btn btn-primary"  data-clipboard-action="copy" data-clipboard-text=<%= "#{ENV.fetch('APP_URL')}" + group_category_article_path(@group, @category, @article,  anchor: "title")%>>
    <%= fa_icon("link")%>
    </button>
</h2>
    <h4><%= @article.description %></h4>
    <p id="content"><%= markdown @article.body %></p>
    
    Created By: <%= @article.user.name %>
    <%= distance_of_time_in_words(@article.created_at, Time.now)%> days ago
    <br>Updated <%= distance_of_time_in_words(@article.updated_at, Time.now)%> days ago
    <%= link_to fa_icon("pencil-square-o"), edit_group_category_article_path(@group, @category, @article), class: "edit", style: "color: #12B629" if logged_in?(:admin) || logged_in?(:editor) %>
    <%= link_to fa_icon("trash"), group_category_article_path(@group, @category, @article), method: :delete, data: {confirm: "Are you sure you want ro delete this post"}, class: "trash", style: "color: red" if logged_in?(:admin) || logged_in?(:editor)  %>
    <p></p>
    <% if current_user.slack_url.present?%>
      <% if current_user.voted_up_on? @article %>
        <%= link_to 'Unfollow', unfollow_group_category_article_path(@group, @category, @article), method: :put, remote: :true, class: "btn btn-primary" %>      
      <%else%>
        <%= link_to 'Follow', follow_group_category_article_path(@group, @category, @article), method: :put, remote: :true,class: "btn btn-primary" %>      
      <%end%>
    <%else%>
      <div class="alert alert-primary" role="alert">
      Add a <%= link_to 'Slack URL', edit_user_registration_path %> in order to follow this article
      </div>
    <%end%>
    <%= @versions.length  %> Versions Created

    <div class="uk-margin-medium-top border-top padding-top">
      <h3 class="uk-margin-medium-bottom">Comments</h3>
      <ul class="uk-comment-list">
        <li>
          <article class="uk-comment uk-visible-toggle">
            <div class="uk-comment-body">
              <div id="comments" data-article-id="<%= @article.id%>">
                <%= render @article.comments %>
               </div>
            </div>
          </article>
        </li>
      </ul>
  
      <div class="reply uk-margin-medium-top padding-top">
        <h3 class="uk-margin-medium-bottom">Leave a Comment</h3>
        <%= form_for @comment, url: '#' do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <%= f.text_area :content, class: 'form-control', placeholder: "Post a Comment", rows: "5" %>
              </div>
            </div>
          </div>
          
          <button type="submit" class="btn btn-primary myspace">Submit</button>
          <%= link_to "Back", :back,  class: "btn btn-primary myspace"%>
        <%end%>
      </div>
    </div>
  </div>
</div>

<script>

$(document).ready(function(){  
  
    var clipboard = new Clipboard('.clipboard-btn');
    clipboard.on('success', function(e) {
    "You've successfully copied the link"
  });

  clipboard.on('error', function(e) {
    // add your custom error code here.
  });
      
  });

  </script>

app/views/articles/tagged.html.erb
div class="uk-section section-sub-nav uk-padding-remove">
  <div class="uk-container">
    <div uk-grid>
      <div class="uk-width-2-3@m">
        <ul class="uk-breadcrumb uk-visible@m">
          <li><%= link_to "Home", root_path %> </li>
          <li><span><%= link_to @category.name.capitalize, group_category_path(@group, @category)%></span></li>
        </ul>
      </div>
      <%= render 'categories/searchbar' %>
    </div>
    <div class="border-top"></div>
  </div>
</div>

<div class="uk-section uk-section-small uk-padding-remove-bottom section-content">
  <div class="uk-container uk-position-relative">
    <% if @root[0].present? %>
      <a class="btn btn-primary myspace" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        View Root Doc
      </a>

      <div class="collapse" id="collapseExample">
        <%= markdown @root[0].body%>
        <hr>
      </div>
    <%end%>
    <div uk-grid>
      <div class="uk-width-3-4@m">
        <article class="uk-article">
          <header>
            <h1 class="uk-article-title uk-margin-bottom"><%= @category.name.capitalize%> Articles</h1>
          </header>
          <%= render 'shared/articles'%>
        </article>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){  
  
    var clipboard = new Clipboard('.clipboard-btn');
    clipboard.on('success', function(e) {
    "You've successfully copied the link"
  });

  clipboard.on('error', function(e) {
    // add your custom error code here.
  });

      
  });

  </script>