config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  as :user do
    get 'my_account/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'my_account/' => 'registrations#update', :as => 'update_user_registration'
    get 'my_account' => 'registrations#show', :as => 'user_registration'
    end
  get '/myarticles' => 'users#article'
  
  resources :groups, only: [:index, :show] do
    get '/myarticles' => 'users#article'
    resources :categories, except: [:index] do
      collection do
          get 'search'
          get 'autocomplete'
    	 end
      resources :articles do
        collection do
          get 'search'
          get :deleted
    	  end
    	  member do
          get :toggle_status
          put :follow
          put :unfollow
        end
    	  resources :versions, only: [:destroy] do
           member do
            get :diff, to: 'versions#diff'
            patch :rollback, to: 'versions#rollback'
          end
        end
      end
    end
  end
  
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  mount ActionCable.server => '/cable'
  root to: "groups#index"
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor, :user], multiple: false)                                          ##
  ############################################################################################ 
 

  acts_as_paranoid
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :comments
  has_many :article_uploads, through: :articles
  def name
   if self.first_name.nil?
     " "
    else
      self.first_name + " " + self.last_name
    end
  end
  
  def self.find_version_author(version)
    find(version.terminator)   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  
  def search
    if params[:search]
      @articles = Article.page.where('name ILIKE ?', "%" + params[:search] + "%" ).where(user_id: current_user.id).per(5).latest
    end 
  end
  
  def article
    @articles = Article.where(user_id: current_user.id).page(params[:page]).per(5)
  end
  
  def set_group
    @group = Group.friendly.find(params[:group_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/article.html.erb
<div class="uk-section section-sub-nav uk-padding-remove">
  <div class="uk-container">
    <div uk-grid>
      <div class="uk-width-2-3@m">
        <ul class="uk-breadcrumb uk-visible@m">
          <li><%= link_to "Home", root_path %></li>
          <li><span><%= current_user.name%></span></li>
        </ul>
      </div>
      
    </div>
    <div class="border-top"></div>
  </div>
</div>

<div class="uk-section uk-section-small uk-padding-remove-bottom section-content">
  <div class="uk-container uk-position-relative">
    <div uk-grid>
      <div class="uk-width-3-4@m">
        <article class="uk-article">
          <header>
            <h1 class="uk-article-title uk-margin-bottom"><%= current_user.name%>'s Authored Articles</h1>
          </header>
          <% @articles.each do |article|%>
          <h2><%= link_to article.name, group_category_article_path(@group, Category.find(article.category_id), article) %>
            <%= link_to fa_icon('check-circle'), toggle_status_group_category_article_path(@group, Category.find(article.category_id), article),  style: article_status_color(article)%>
          </h2>
          <h4><%= article.description %></h4>
          Created by: <%= article.user.email %>
          <%end%>
          <%= paginate @articles %>
          <%= link_to "Back", :back, class: "btn btn-primary" %>
        </article>
      </div>
    </div>
  </div>
</div>