config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, :skip => [:registrations] , :controllers => { registrations: "registrations"}
  as :user do
    get 'my_account/edit' => 'registrations#edit', :as => 'edit_user_registration'
    put 'my_account/' => 'registrations#update', :as => 'update_user_registration'
    get 'my_account' => 'registrations#show', :as => 'user_registration'
    end
  get '/myarticles' => 'users#article'
  
  resources :groups, only: [:index, :show] do
    get '/myarticles' => 'users#article'
    resources :categories, except: [:index] do
      collection do
          get 'search'
          get 'autocomplete'
    	 end
      resources :articles do
        collection do
          get 'search'
          get :deleted
    	  end
    	  member do
          get :toggle_status
          put :follow
          put :unfollow
        end
    	  resources :versions, only: [:destroy] do
           member do
            get :diff, to: 'versions#diff'
            patch :rollback, to: 'versions#rollback'
          end
        end
      end
    end
  end
  
  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end
  mount ActionCable.server => '/cable'
  root to: "groups#index"
end

app/views/shared/_application_nav.html.erb
<nav class="uk-navbar-container uk-margin uk-navbar-transparent uk-light">
  <div class="uk-container">
    <div uk-navbar>
      <div class="uk-navbar-left">
        <%= link_to "KnowledgeBase", group_path(@group), class:"uk-navbar-item uk-logo uk-text-uppercase uk-margin-small-right" %>
      </div>
        <div class="uk-navbar-right">
        <ul class="uk-navbar-nav uk-text-uppercase uk-visible@m uk-margin-medium-left">
          <li><%= link_to "Home", groups_path(@group)%></li>
          <% if !(current_page?(edit_user_registration_path))%>
          <li>
            <li><%= link_to "Categories", group_path(@group)%>
              <div class="uk-navbar-dropdown">
                <ul class="uk-nav uk-navbar-dropdown-nav" 
                  <% @group.categories.each do |category|%>
                    <li><%= link_to category.name, group_category_path(@group, category) %></li>
                  <%end%>
                </ul>
              </div> 
            </li>
            <%end%>
            <% if !(current_page?(group_categories_path(@group)))%>
              <% if !(current_page?(root_path))%>
                <% if  !(current_page?(myarticles_path)) && @category.present? %>
                  <li><%= link_to "Create New Article", new_group_category_article_path(@group, @category) if logged_in?(:admin) || logged_in?(:editor) %></li>
                  <li><%= link_to "Deleted Articles",  deleted_group_category_articles_path(@group, @category, @articles)if logged_in?(:admin) || logged_in?(:editor)%> </li>
                <%end%>
              <%end%>
            <%end%>
            <li><%= link_to "My Account", user_registration_path(@group)  if current_user %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete if current_user %></li>
            <li><%= link_to "Admin", rails_admin_path  if logged_in?(:admin)%></li>
            <li><%= link_to  "Login", new_user_session_path if !current_user%></li>
      
        </ul>
        <a class="uk-navbar-toggle uk-hidden@m" href="#offcanvas" uk-navbar-toggle-icon uk-toggle></a>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_articles.html.erb
<% @articles.each do |article|%>
    <h2 id=<%= "article-#{article.id}"%>><%= link_to article.name, group_category_article_path(@group, @category, article) %> 
    <% if !current_page?(search_group_categories_path)%>
        <button class= "clipboard-btn btn btn-primary"  data-clipboard-action="copy" data-clipboard-text=<%=  "#{ENV.fetch('APP_URL')}" + group_category_path(@group, @category,  anchor: "article-#{article.id}")%>>
            <%= fa_icon("link")%>
        </button>
    <%end%>
    </h2>
    <h4><%= article.description %></h4>
    
    Created by: <%= article.user.email %>
    <span class="badge btn-primary"><%= article.category.name%></span>
    <hr>
<%end%>
<br>
<%= paginate @articles %>

app/views/shared/_footer.html.erb
<footer id="footer" class="uk-section uk-margin-remove uk-text-small uk-text-muted border-top">
  <div class="uk-container">
    <div class="uk-child-width-1-2@m uk-text-center" uk-grid>
      <div class="uk-text-right@m">
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: facebook"></a>
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: google"></a>
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: vimeo"></a>
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: instagram"></a>
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: twitter"></a>
        <a href="#" class="uk-icon-link uk-margin-small-right" uk-icon="icon: youtube"></a>
      </div>
      <div class="uk-flex-first@m uk-text-left@m">
        <p class="uk-text-small">Copyright 2018 </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_jumbotron.html.erb
<div class="uk-container hero">
  <h1 class="uk-heading-primary uk-text-center uk-margin-large-top uk-light">Create a Knowledge Base with Ease</h1>
  <div class="uk-flex uk-flex-center">
  </div>
</div>